
# set easyflash env psm size
ifndef CONFIG_ENABLE_PSM_EF_SIZE
CPPFLAGS += -DCONFIG_PSM_EASYFLASH_SIZE=4096
else
ifeq ($(CONFIG_ENABLE_PSM_EF_SIZE),4K)
CPPFLAGS += -DCONFIG_PSM_EASYFLASH_SIZE=4096
else ifeq ($(CONFIG_ENABLE_PSM_EF_SIZE),8K)
CPPFLAGS += -DCONFIG_PSM_EASYFLASH_SIZE=8192
else ifeq ($(CONFIG_ENABLE_PSM_EF_SIZE),16K)
CPPFLAGS += -DCONFIG_PSM_EASYFLASH_SIZE=16384
else
$(error error, CONFIG_ENABLE_PSM_EF_SIZE only support 4K、8K、16K in $(PROJECT_PATH)/proj_config.mk.)
endif
endif

ifeq ($(CONFIG_FREERTOS_TICKLESS_MODE),0)
CPPFLAGS += -DconfigUSE_TICKLESS_IDLE=0
CFLAGS += -DconfigUSE_TICKLESS_IDLE=0
endif

ifeq ($(CONFIG_WIFI),0)
CPPFLAGS += -DFEATURE_WIFI_DISABLE=1
CFLAGS += -DFEATURE_WIFI_DISABLE=1
endif

ifeq ($(CONFIG_DTS_INAPP),1)
CPPFLAGS += -DCONFIG_USER_DTS_INAPP=1
endif

ifeq ($(CONFIG_SYS_BIG_DEBUG_BUFFER),1)
CPPFLAGS += -DSYS_BIG_DEBUG_BUFFER=1
endif
ifeq ($(CONFIG_ENABLE_ETHMAC), 1)
CPPFLAGS += -DETHMAC_ENABLE

endif
ifeq ($(CONFIG_SYS_USER_VFS_ROMFS_ENABLE),1)
CPPFLAGS += -DSYS_USER_VFS_ROMFS_ENABLE
endif

ifeq ($(CONFIG_ENABLE_CORE_CLK50),1)
CFLAGS += -DCORE_CLK50M
endif

ifeq ($(CONFIG_ENABLE_DBG_UARTID_0),1)
CFLAGS += -DLOG_UART_ID_0
endif

ifeq ($(CONFIG_ENABLE_DBG_UART_WLAN),1)
CFLAGS += -DWLAN_DEBUG
endif

ifeq ($(CONFIG_COMPONENT_BUGKILLER_ENABLE),1)
CPPFLAGS += -DCFG_COMPONENT_BUGKILLER_ENABLE
endif

ifeq ($(CONFIG_USB_CAM_ENABLE),1)
CFLAGS += -DCONFIG_USB_DCACHE_ENABLE
endif

ifeq ($(CONFIG_USB_HIGHSPEED_ENABLE),1)
CFLAGS += -DCONFIG_USB_HS
endif

ifneq ($(CONFIG_CLI_CMD_ENABLE), 0)
CPPFLAGS += -DCONFIG_CLI_CMD_ENABLE
endif

ifeq ($(CONFIG_CHIP_NAME),BL616)
CFLAGS += -DCHIP_CODE_BL616
CFLAGS += -DBL616
CFLAGS += -DWL_BL616
endif

ifeq ($(CONFIG_CHIP_NAME),WB03)
CFLAGS += -DWL_WB03
endif

ifeq ($(CONFIG_CHIP_NAME),BL618M)
CFLAGS += -DWL_BL618M
endif
