FROM debian:buster

RUN set -eux \
    && export DEBIAN_FRONTEND=noninteractive \
    && apt-get update;apt-get upgrade \
    && apt install -y build-essential python3 python3-pip \
    && apt-get -y --purge autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
    
    
RUN pip3 install fdt

COPY . /src
WORKDIR /src
ENTRYPOINT /bin/bash
