
CFLAGS += -D__int64_t_defined=1
CPPFLAGS += -D__int64_t_defined=1

CFLAGS += -DOPENTHREAD_CONFIG_FILE=\"include/openthread-core-config.h\"
CFLAGS += -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE=\"include/openthread-core-config.h\"
CFLAGS += -DOPENTHREAD_CORE_CONFIG_PLATFORM_CHECK_FILE=\"include/openthread-core-config-check.h\"
CPPFLAGS += -DOPENTHREAD_CONFIG_FILE=\"include/openthread-core-config.h\"
CPPFLAGS += -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE=\"include/openthread-core-config.h\"
CPPFLAGS += -DOPENTHREAD_CORE_CONFIG_PLATFORM_CHECK_FILE=\"include/openthread-core-config-check.h\"

CFLAGS += -DOT_CLI_UART_LOCK_HDR_FILE=\"openthread_port.h\"
CPPFLAGS += -DOT_CLI_UART_LOCK_HDR_FILE=\"openthread_port.h\"

CFLAGS += -DPACKAGE_NAME=\"OPENTHREAD\"
CFLAGS += -DPACKAGE_VERSION=\"9ea34d1e2\"
CFLAGS += -DMBEDTLS_CONFIG_FILE=\"mbedtls-config.h\"
CPPFLAGS += -DPACKAGE_NAME=\"OPENTHREAD\"
CPPFLAGS += -DPACKAGE_VERSION=\"9ea34d1e2\"
CPPFLAGS += -DMBEDTLS_CONFIG_FILE=\"mbedtls-config.h\"

CFLAGS += -DOPENTHREAD_EXAMPLES_SIMULATION=0
CPPFLAGS += -DOPENTHREAD_EXAMPLES_SIMULATION=0

CFLAGS += -DOPENTHREAD_CONFIG_MAC_SOFTWARE_TX_TIMING_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_MAC_SOFTWARE_TX_TIMING_ENABLE=1

CFLAGS += -DOPENTHREAD_CONFIG_IP6_SLAAC_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_IP6_SLAAC_ENABLE=1

CFLAGS += -DOPENTHREAD_CONFIG_THREAD_VERSION=3
CPPFLAGS += -DOPENTHREAD_CONFIG_THREAD_VERSION=3

CFLAGS += -DOPENTHREAD_CONFIG_PLATFORM_USEC_TIMER_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_PLATFORM_USEC_TIMER_ENABLE=1

CFLGAS += -DOT_FREERTOS_ENABLE=1
CPPFLAGS += -DOT_FREERTOS_ENABLE=1

CFLAGS += -DOPENTHREAD_CONFIG_LEGACY_ENABLE=0
CPPFLAGS += -DOPENTHREAD_CONFIG_LEGACY_ENABLE=0

CFLAGS += -DOPENTHREAD_PLATFORM_POSIX=0
CPPFLAGS += -DOPENTHREAD_PLATFORM_POSIX=0

CFLAGS += -DOPENTHREAD_POSIX=0
CPPFLAGS += -DOPENTHREAD_POSIX=0

CFLAGS += -DOPENTHREAD_CONFIG_ECDSA_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_ECDSA_ENABLE=1

CFLAGS += -DOPENTHREAD_CONFIG_SRP_CLIENT_ENABLE=1
CPPFLAGS += -DOPENTHREAD_CONFIG_SRP_CLIENT_ENABLE=1

CFLAGS += -DOPENTHREAD_ENABLE_VENDOR_EXTENSION=0
CPPFLAGS += -DOPENTHREAD_ENABLE_VENDOR_EXTENSION=0

CFLAGS += -DOPENTHREAD_CONFIG_MLE_LINK_METRICS_SUBJECT_ENABLE=0
CPPFLAGS += -DOPENTHREAD_CONFIG_MAC_CSL_RECEIVER_ENABLE=0

CFLAGS += -DOPENTHREAD_CONFIG_MAC_CSL_RECEIVER_ENABLE=0
CPPFLAGS += -DOPENTHREAD_CONFIG_MLE_LINK_METRICS_SUBJECT_ENABLE=0

CFLAGS += -DOPENTHREAD_CONFIG_MAC_CSL_TRANSMITTER_ENABLE=0
CPPFLAGS += -DOPENTHREAD_CONFIG_MAC_CSL_TRANSMITTER_ENABLE=0

CFLAGS += -Wimplicit-fallthrough=0 -Wno-switch-default
CPPFLAGS += -Wimplicit-fallthrough=0 -Wno-switch-default