#
#compiler flag config domain
#
#CONFIG_TOOLPREFIX :=
#CONFIG_OPTIMIZATION_LEVEL_RELEASE := 1
#CONFIG_M4_SOFTFP := 1

#
#board config domain
#
CONFIG_BOARD_FLASH_SIZE := 2

#firmware config domain
#

#set CONFIG_ENABLE_ACP to 1 to enable ACP, set to 0 or comment this line to disable
CONFIG_ENABLE_PSM_RAM:=1
CONFIG_BL_IOT_FW_AP:=1
CONFIG_BL_IOT_FW_AMPDU:=0
CONFIG_BL_IOT_FW_AMSDU:=0
CONFIG_BL_IOT_FW_P2P:=0

LOG_ENABLED_COMPONENTS:=hosal

# set easyflash env psm size, only support 4K、8K、16K options
CONFIG_ENABLE_PSM_EF_SIZE:=16K

CONFIG_FREERTOS_TICKLESS_MODE:=0

ifeq ($(CPU_ID), M0)
CONFIG_WIFI:=1
CONFIG_CPU_E907:=1
CONFIG_WIFI_PKT_INPUT_HOOK := 1
CONFIG_WIFI_PKT_OUTPUT_HOOK := 1
endif

CONFIG_ENABLE_FP:=1

ifeq ($(CPU_ID), D0)
CONFIG_LINK_CUSTOMER:=1
endif
