#
#compiler flag config domain
#

#
#board config domain
#
CONFIG_BOARD_FLASH_SIZE := 8

#firmware config domain
#

#set CONFIG_ENABLE_ACP to 1 to enable ACP, set to 0 or comment this line to disable
#CONFIG_ENABLE_ACP:=1
CONFIG_BL_IOT_FW_AP:=1
CONFIG_BL_IOT_FW_AMPDU:=0
CONFIG_BL_IOT_FW_AMSDU:=0
CONFIG_BL_IOT_FW_P2P:=0
CONFIG_ENABLE_PSM_RAM:=0
CONFIG_ENABLE_VFS_ROMFS:=1

# set easyflash env psm size, only support 4K/8K/16K options
CONFIG_ENABLE_PSM_EF_SIZE:=16K

CONFIG_FREERTOS_TICKLESS_MODE:=0
CONFIG_PHY_CLI:=1
CONFIG_WIFI:=1
CONFIG_PHY_FPGA:=0
CONFIG_PHY_BZ_ONLY:=0
CONFIG_PHY_CLI_SUPPORT_SRAM:=0

CONFIG_USE_STD_DRIVER:=1
CONFIG_BLE_HOST_DISABLE:=0
CONFIG_DBG_RUN_ON_FPGA:=0
CONFIG_DISABLE_PRINT:=0
CONFIG_BLE_USE_MAC2:=0
CONFIG_PHY_ANT2:=0
CONF_ENABLE_COREDUMP:=1

LOG_ENABLED_COMPONENTS:=hosal
CONFIG_COMPONENT_BUGKILLER_ENABLE:=1
CONFIG_USB_CAM_ENABLE:= 1
CONFIG_USB_HIGHSPEED_ENABLE:= 0
CONFIG_BT_ENABLE:=0

#EXTRA_LDFLAGS += --specs=nano.specs
CFLAGS += -DBFLB_USE_HAL_DRIVER -DCPU_M0 -DARCH_RISCV -DSYS_USER_VFS_ROMFS_ENABLE

