
# set easyflash env psm size
ifndef CONFIG_ENABLE_PSM_EF_SIZE
CPPFLAGS += -DCONFIG_PSM_EASYFLASH_SIZE=4096
else
ifeq ($(CONFIG_ENABLE_PSM_EF_SIZE),4K)
CPPFLAGS += -DCONFIG_PSM_EASYFLASH_SIZE=4096
else ifeq ($(CONFIG_ENABLE_PSM_EF_SIZE),8K)
CPPFLAGS += -DCONFIG_PSM_EASYFLASH_SIZE=8192
else ifeq ($(CONFIG_ENABLE_PSM_EF_SIZE),16K)
CPPFLAGS += -DCONFIG_PSM_EASYFLASH_SIZE=16384
else
$(error error, CONFIG_ENABLE_PSM_EF_SIZE only support 4K、8K、16K in $(PROJECT_PATH)/proj_config.mk.)
endif
endif

ifeq ($(CONFIG_FREERTOS_TICKLESS_MODE),0)
CPPFLAGS += -DconfigUSE_TICKLESS_IDLE=0
CFLAGS += -DconfigUSE_TICKLESS_IDLE=0
endif

ifeq ($(CONFIG_WIFI),0)
CPPFLAGS += -DFEATURE_WIFI_DISABLE=1
CFLAGS += -DFEATURE_WIFI_DISABLE=1
endif

ifeq ($(CONFIG_DTS_INAPP),1)
CPPFLAGS += -DCONFIG_USER_DTS_INAPP=1
endif

ifeq ($(CONFIG_SYS_BIG_DEBUG_BUFFER),1)
CPPFLAGS += -DSYS_BIG_DEBUG_BUFFER=1
endif
