#ifndef __VERSION_BTHOST_H__
#define __VERSION_BTHOST_H__
#define  BT_HOST_VERSION_MACSW_NUMBER "1.6.5"
#define  BT_HOST_VERSION_MACSW_MAJOR 1
#define  BT_HOST_VERSION_MACSW_MINOR 6
#define  BT_HOST_VERSION_MACSW_PATCH 5
#endif
